export const  data = [
    {
      "city": "Ljubljana", 
      "lat": "46.0514", 
      "lng": "14.5061", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ljubljana", 
      "capital": "primary", 
      "population": "286745", 
      "population_proper": "284293"
    }, 
    {
      "city": "Maribor", 
      "lat": "46.5575", 
      "lng": "15.6456", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Maribor", 
      "capital": "admin", 
      "population": "97019", 
      "population_proper": "96211"
    }, 
    {
      "city": "Kranj", 
      "lat": "46.2333", 
      "lng": "14.3667", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranj", 
      "capital": "admin", 
      "population": "37941", 
      "population_proper": "37553"
    }, 
    {
      "city": "Celje", 
      "lat": "46.2358", 
      "lng": "15.2675", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Celje", 
      "capital": "admin", 
      "population": "37872", 
      "population_proper": "37872"
    }, 
    {
      "city": "Koper", 
      "lat": "45.5500", 
      "lng": "13.7333", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Koper", 
      "capital": "admin", 
      "population": "25753", 
      "population_proper": "25753"
    }, 
    {
      "city": "Velenje", 
      "lat": "46.3625", 
      "lng": "15.1144", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Velenje", 
      "capital": "admin", 
      "population": "25594", 
      "population_proper": "25594"
    }, 
    {
      "city": "Novo Mesto", 
      "lat": "45.8000", 
      "lng": "15.1667", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Novo Mesto", 
      "capital": "admin", 
      "population": "24183", 
      "population_proper": "24183"
    }, 
    {
      "city": "Ptuj", 
      "lat": "46.4194", 
      "lng": "15.8694", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ptuj", 
      "capital": "admin", 
      "population": "17959", 
      "population_proper": "17959"
    }, 
    {
      "city": "Kamnik", 
      "lat": "46.2257", 
      "lng": "14.6120", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kamnik", 
      "capital": "admin", 
      "population": "13880", 
      "population_proper": "13880"
    }, 
    {
      "city": "Trbovlje", 
      "lat": "46.1500", 
      "lng": "15.0500", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Trbovlje", 
      "capital": "admin", 
      "population": "13822", 
      "population_proper": "13822"
    }, 
    {
      "city": "Jesenice", 
      "lat": "46.4366", 
      "lng": "14.0602", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Jesenice", 
      "capital": "admin", 
      "population": "13338", 
      "population_proper": "13338"
    }, 
    {
      "city": "Domžale", 
      "lat": "46.1394", 
      "lng": "14.5950", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Domžale", 
      "capital": "admin", 
      "population": "13204", 
      "population_proper": "13204"
    }, 
    {
      "city": "Nova Gorica", 
      "lat": "45.9558", 
      "lng": "13.6433", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Nova Gorica", 
      "capital": "admin", 
      "population": "13031", 
      "population_proper": "13031"
    }, 
    {
      "city": "Izola", 
      "lat": "45.5344", 
      "lng": "13.6675", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Izola", 
      "capital": "admin", 
      "population": "11682", 
      "population_proper": "11682"
    }, 
    {
      "city": "Škofja Loka", 
      "lat": "46.1672", 
      "lng": "14.3030", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Škofja Loka", 
      "capital": "admin", 
      "population": "11671", 
      "population_proper": "11671"
    }, 
    {
      "city": "Murska Sobota", 
      "lat": "46.6667", 
      "lng": "16.1667", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Murska Sobota", 
      "capital": "admin", 
      "population": "11107", 
      "population_proper": "11107"
    }, 
    {
      "city": "Postojna", 
      "lat": "45.7759", 
      "lng": "14.2137", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Postojna", 
      "capital": "admin", 
      "population": "9605", 
      "population_proper": "9605"
    }, 
    {
      "city": "Logatec", 
      "lat": "45.9167", 
      "lng": "14.2297", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Logatec", 
      "capital": "admin", 
      "population": "9091", 
      "population_proper": "9091"
    }, 
    {
      "city": "Vrhnika", 
      "lat": "45.9624", 
      "lng": "14.2937", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vrhnika", 
      "capital": "admin", 
      "population": "8888", 
      "population_proper": "8888"
    }, 
    {
      "city": "Slovenska Bistrica", 
      "lat": "46.3903", 
      "lng": "15.5750", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Slovenska Bistrica", 
      "capital": "admin", 
      "population": "8219", 
      "population_proper": "8219"
    }, 
    {
      "city": "Kočevje", 
      "lat": "45.6430", 
      "lng": "14.8594", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kočevje", 
      "capital": "admin", 
      "population": "8151", 
      "population_proper": "8151"
    }, 
    {
      "city": "Grosuplje", 
      "lat": "45.9551", 
      "lng": "14.6562", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Grosuplje", 
      "capital": "admin", 
      "population": "7703", 
      "population_proper": "7703"
    }, 
    {
      "city": "Ravne na Koroškem", 
      "lat": "46.5437", 
      "lng": "14.9642", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ravne na Koroškem", 
      "capital": "admin", 
      "population": "7363", 
      "population_proper": "7363"
    }, 
    {
      "city": "Slovenj Gradec", 
      "lat": "46.5094", 
      "lng": "15.0792", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Slovenj Gradec", 
      "capital": "admin", 
      "population": "7249", 
      "population_proper": "7249"
    }, 
    {
      "city": "Krško", 
      "lat": "45.9500", 
      "lng": "15.4833", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Krško", 
      "capital": "admin", 
      "population": "7217", 
      "population_proper": "7217"
    }, 
    {
      "city": "Ajdovščina", 
      "lat": "45.8861", 
      "lng": "13.9097", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ajdovščina", 
      "capital": "admin", 
      "population": "6843", 
      "population_proper": "6843"
    }, 
    {
      "city": "Brežice", 
      "lat": "45.9048", 
      "lng": "15.5922", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Brežice", 
      "capital": "admin", 
      "population": "6843", 
      "population_proper": "6843"
    }, 
    {
      "city": "Litija", 
      "lat": "46.0667", 
      "lng": "14.8167", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Litija", 
      "capital": "admin", 
      "population": "6673", 
      "population_proper": "6673"
    }, 
    {
      "city": "Mengeš", 
      "lat": "46.1626", 
      "lng": "14.5680", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mengeš", 
      "capital": "admin", 
      "population": "6119", 
      "population_proper": "6119"
    }, 
    {
      "city": "Lucija", 
      "lat": "45.5067", 
      "lng": "13.6016", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Piran", 
      "capital": "", 
      "population": "6057", 
      "population_proper": "6057"
    }, 
    {
      "city": "Sežana", 
      "lat": "45.7034", 
      "lng": "13.8706", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sežana", 
      "capital": "admin", 
      "population": "6037", 
      "population_proper": "6037"
    }, 
    {
      "city": "Zagorje", 
      "lat": "46.1342", 
      "lng": "14.9942", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Zagorje ob Savi", 
      "capital": "admin", 
      "population": "6023", 
      "population_proper": "6023"
    }, 
    {
      "city": "Radovljica", 
      "lat": "46.3425", 
      "lng": "14.1721", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Radovljica", 
      "capital": "admin", 
      "population": "5981", 
      "population_proper": "5981"
    }, 
    {
      "city": "Idrija", 
      "lat": "46.0025", 
      "lng": "14.0275", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Idrija", 
      "capital": "admin", 
      "population": "5886", 
      "population_proper": "5886"
    }, 
    {
      "city": "Črnomelj", 
      "lat": "45.5711", 
      "lng": "15.1889", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Črnomelj", 
      "capital": "admin", 
      "population": "5496", 
      "population_proper": "5496"
    }, 
    {
      "city": "Medvode", 
      "lat": "46.1382", 
      "lng": "14.4147", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Medvode", 
      "capital": "admin", 
      "population": "5380", 
      "population_proper": "5380"
    }, 
    {
      "city": "Slovenske Konjice", 
      "lat": "46.3383", 
      "lng": "15.4233", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Slovenske Konjice", 
      "capital": "admin", 
      "population": "5157", 
      "population_proper": "5157"
    }, 
    {
      "city": "Rogaška Slatina", 
      "lat": "46.2314", 
      "lng": "15.6381", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Rogaška Slatina", 
      "capital": "admin", 
      "population": "5082", 
      "population_proper": "5082"
    }, 
    {
      "city": "Žalec", 
      "lat": "46.2510", 
      "lng": "15.1639", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Žalec", 
      "capital": "admin", 
      "population": "5000", 
      "population_proper": "5000"
    }, 
    {
      "city": "Hrastnik", 
      "lat": "46.1479", 
      "lng": "15.1528", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hrastnik", 
      "capital": "admin", 
      "population": "4962", 
      "population_proper": "4962"
    }, 
    {
      "city": "Šentjur", 
      "lat": "46.2176", 
      "lng": "15.3960", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šentjur", 
      "capital": "admin", 
      "population": "4940", 
      "population_proper": "4940"
    }, 
    {
      "city": "Bled", 
      "lat": "46.3688", 
      "lng": "14.1140", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Bled", 
      "capital": "admin", 
      "population": "4929", 
      "population_proper": "4929"
    }, 
    {
      "city": "Prevalje", 
      "lat": "46.5438", 
      "lng": "14.9119", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Prevalje", 
      "capital": "admin", 
      "population": "4620", 
      "population_proper": "4620"
    }, 
    {
      "city": "Sevnica", 
      "lat": "46.0092", 
      "lng": "15.3041", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sevnica", 
      "capital": "admin", 
      "population": "4533", 
      "population_proper": "4533"
    }, 
    {
      "city": "Ilirska Bistrica", 
      "lat": "45.5679", 
      "lng": "14.2527", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ilirska Bistrica", 
      "capital": "admin", 
      "population": "4323", 
      "population_proper": "4323"
    }, 
    {
      "city": "Ruše", 
      "lat": "46.5386", 
      "lng": "15.5154", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ruše", 
      "capital": "admin", 
      "population": "4208", 
      "population_proper": "4208"
    }, 
    {
      "city": "Cerknica", 
      "lat": "45.7964", 
      "lng": "14.3581", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cerknica", 
      "capital": "admin", 
      "population": "4018", 
      "population_proper": "4018"
    }, 
    {
      "city": "Trebnje", 
      "lat": "45.9104", 
      "lng": "15.0086", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Trebnje", 
      "capital": "admin", 
      "population": "3927", 
      "population_proper": "3927"
    }, 
    {
      "city": "Trzin", 
      "lat": "46.1353", 
      "lng": "14.5600", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Trzin", 
      "capital": "admin", 
      "population": "3925", 
      "population_proper": "3925"
    }, 
    {
      "city": "Miklavž na Dravskem Polju", 
      "lat": "46.5057", 
      "lng": "15.6993", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Miklavž na Dravskem Polju", 
      "capital": "admin", 
      "population": "3808", 
      "population_proper": "3808"
    }, 
    {
      "city": "Piran", 
      "lat": "45.5283", 
      "lng": "13.5683", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Piran", 
      "capital": "admin", 
      "population": "3730", 
      "population_proper": "3730"
    }, 
    {
      "city": "Šempeter pri Gorici", 
      "lat": "45.9284", 
      "lng": "13.6378", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šempeter-Vrtojba", 
      "capital": "admin", 
      "population": "3694", 
      "population_proper": "3694"
    }, 
    {
      "city": "Tržič", 
      "lat": "46.3581", 
      "lng": "14.2930", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Tržič", 
      "capital": "admin", 
      "population": "3670", 
      "population_proper": "3670"
    }, 
    {
      "city": "Žiri", 
      "lat": "46.0469", 
      "lng": "14.1097", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Žiri", 
      "capital": "admin", 
      "population": "3657", 
      "population_proper": "3657"
    }, 
    {
      "city": "Ribnica", 
      "lat": "45.7400", 
      "lng": "14.7308", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ribnica", 
      "capital": "admin", 
      "population": "3612", 
      "population_proper": "3612"
    }, 
    {
      "city": "Tolmin", 
      "lat": "46.1857", 
      "lng": "13.7352", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Tolmin", 
      "capital": "admin", 
      "population": "3525", 
      "population_proper": "3525"
    }, 
    {
      "city": "Laško", 
      "lat": "46.1563", 
      "lng": "15.2386", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Laško", 
      "capital": "admin", 
      "population": "3288", 
      "population_proper": "3288"
    }, 
    {
      "city": "Lenart v Slovenskih Goricah", 
      "lat": "46.5742", 
      "lng": "15.8322", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Lenart", 
      "capital": "admin", 
      "population": "3285", 
      "population_proper": "3285"
    }, 
    {
      "city": "Ljutomer", 
      "lat": "46.5168", 
      "lng": "16.2027", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ljutomer", 
      "capital": "admin", 
      "population": "3270", 
      "population_proper": "3270"
    }, 
    {
      "city": "Metlika", 
      "lat": "45.6517", 
      "lng": "15.3200", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Metlika", 
      "capital": "admin", 
      "population": "3229", 
      "population_proper": "3229"
    }, 
    {
      "city": "Ankaran", 
      "lat": "45.5793", 
      "lng": "13.7379", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ankaran", 
      "capital": "admin", 
      "population": "3224", 
      "population_proper": "3224"
    }, 
    {
      "city": "Brezovica", 
      "lat": "46.0207", 
      "lng": "14.4178", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Brezovica", 
      "capital": "admin", 
      "population": "3221", 
      "population_proper": "3221"
    }, 
    {
      "city": "Solkan", 
      "lat": "45.9695", 
      "lng": "13.6455", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Nova Gorica", 
      "capital": "", 
      "population": "3216", 
      "population_proper": "3216"
    }, 
    {
      "city": "Bistrica pri Tržiču", 
      "lat": "46.3581", 
      "lng": "14.2930", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Tržič", 
      "capital": "", 
      "population": "3187", 
      "population_proper": "3187"
    }, 
    {
      "city": "Mežica", 
      "lat": "46.5206", 
      "lng": "14.8536", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mežica", 
      "capital": "admin", 
      "population": "3176", 
      "population_proper": "3176"
    }, 
    {
      "city": "Šenčur", 
      "lat": "46.2430", 
      "lng": "14.4181", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šenčur", 
      "capital": "admin", 
      "population": "3121", 
      "population_proper": "3121"
    }, 
    {
      "city": "Dravograd", 
      "lat": "46.5903", 
      "lng": "15.0236", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dravograd", 
      "capital": "admin", 
      "population": "3088", 
      "population_proper": "3088"
    }, 
    {
      "city": "Gornja Radgona", 
      "lat": "46.6752", 
      "lng": "15.9926", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Gornja Radgona", 
      "capital": "admin", 
      "population": "3086", 
      "population_proper": "3086"
    }, 
    {
      "city": "Železniki", 
      "lat": "46.2182", 
      "lng": "14.1592", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Železniki", 
      "capital": "admin", 
      "population": "3069", 
      "population_proper": "3069"
    }, 
    {
      "city": "Lendava", 
      "lat": "46.5631", 
      "lng": "16.4519", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Lendava", 
      "capital": "admin", 
      "population": "2954", 
      "population_proper": "2954"
    }, 
    {
      "city": "Rogašovci", 
      "lat": "46.8053", 
      "lng": "16.0344", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Rogašovci", 
      "capital": "admin", 
      "population": "2946", 
      "population_proper": "2946"
    }, 
    {
      "city": "Šoštanj", 
      "lat": "46.3798", 
      "lng": "15.0482", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šoštanj", 
      "capital": "admin", 
      "population": "2933", 
      "population_proper": "2933"
    }, 
    {
      "city": "Zreče", 
      "lat": "46.3750", 
      "lng": "15.3854", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Zreče", 
      "capital": "admin", 
      "population": "2922", 
      "population_proper": "2922"
    }, 
    {
      "city": "Lesce", 
      "lat": "46.3600", 
      "lng": "14.1564", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Radovljica", 
      "capital": "", 
      "population": "2918", 
      "population_proper": "2918"
    }, 
    {
      "city": "Portorož", 
      "lat": "45.5166", 
      "lng": "13.5800", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Piran", 
      "capital": "", 
      "population": "2866", 
      "population_proper": "2866"
    }, 
    {
      "city": "Radlje ob Dravi", 
      "lat": "46.6152", 
      "lng": "15.2264", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Radlje ob Dravi", 
      "capital": "admin", 
      "population": "2856", 
      "population_proper": "2856"
    }, 
    {
      "city": "Škofljica", 
      "lat": "45.9836", 
      "lng": "14.5761", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Škofljica", 
      "capital": "admin", 
      "population": "2716", 
      "population_proper": "2716"
    }, 
    {
      "city": "Rače", 
      "lat": "46.4529", 
      "lng": "15.6812", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Rače-Fram", 
      "capital": "admin", 
      "population": "2693", 
      "population_proper": "2693"
    }, 
    {
      "city": "Borovnica", 
      "lat": "45.9197", 
      "lng": "14.3572", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Borovnica", 
      "capital": "admin", 
      "population": "2674", 
      "population_proper": "2674"
    }, 
    {
      "city": "Vnanje Gorice", 
      "lat": "46.0025", 
      "lng": "14.4145", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Brezovica", 
      "capital": "", 
      "population": "2605", 
      "population_proper": "2605"
    }, 
    {
      "city": "Vrtojba", 
      "lat": "45.9089", 
      "lng": "13.6364", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šempeter-Vrtojba", 
      "capital": "", 
      "population": "2598", 
      "population_proper": "2598"
    }, 
    {
      "city": "Vojnik", 
      "lat": "46.2933", 
      "lng": "15.3052", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vojnik", 
      "capital": "admin", 
      "population": "2475", 
      "population_proper": "2475"
    }, 
    {
      "city": "Senovo", 
      "lat": "46.0259", 
      "lng": "15.4804", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Krško", 
      "capital": "", 
      "population": "2448", 
      "population_proper": "2448"
    }, 
    {
      "city": "Beltinci", 
      "lat": "46.6060", 
      "lng": "16.2328", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Beltinci", 
      "capital": "admin", 
      "population": "2430", 
      "population_proper": "2430"
    }, 
    {
      "city": "Polzela", 
      "lat": "46.2809", 
      "lng": "15.0740", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Polzela", 
      "capital": "admin", 
      "population": "2351", 
      "population_proper": "2351"
    }, 
    {
      "city": "Muta", 
      "lat": "46.6167", 
      "lng": "15.1667", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Muta", 
      "capital": "admin", 
      "population": "2291", 
      "population_proper": "2291"
    }, 
    {
      "city": "Štore", 
      "lat": "46.2219", 
      "lng": "15.3111", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Štore", 
      "capital": "admin", 
      "population": "2257", 
      "population_proper": "2257"
    }, 
    {
      "city": "Ig", 
      "lat": "45.9692", 
      "lng": "14.5394", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ig", 
      "capital": "admin", 
      "population": "2240", 
      "population_proper": "2240"
    }, 
    {
      "city": "Koroška-Bela", 
      "lat": "46.4367", 
      "lng": "14.1019", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Jesenice", 
      "capital": "", 
      "population": "2206", 
      "population_proper": "2206"
    }, 
    {
      "city": "Ivančna Gorica", 
      "lat": "45.9374", 
      "lng": "14.8029", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ivančna Gorica", 
      "capital": "admin", 
      "population": "2205", 
      "population_proper": "2205"
    }, 
    {
      "city": "Črna na Koroškem", 
      "lat": "46.4697", 
      "lng": "14.8490", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Črna na Koroškem", 
      "capital": "admin", 
      "population": "2201", 
      "population_proper": "2201"
    }, 
    {
      "city": "Rakek", 
      "lat": "45.8145", 
      "lng": "14.3123", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cerknica", 
      "capital": "", 
      "population": "2190", 
      "population_proper": "2190"
    }, 
    {
      "city": "Jagodje", 
      "lat": "45.5282", 
      "lng": "13.6471", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Izola", 
      "capital": "", 
      "population": "2153", 
      "population_proper": "2153"
    }, 
    {
      "city": "Radenci", 
      "lat": "46.6500", 
      "lng": "16.0500", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Radenci", 
      "capital": "admin", 
      "population": "2142", 
      "population_proper": "2142"
    }, 
    {
      "city": "Spodnje Hoče", 
      "lat": "46.4996", 
      "lng": "15.6471", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hoče-Slivnica", 
      "capital": "admin", 
      "population": "2109", 
      "population_proper": "2109"
    }, 
    {
      "city": "Preserje pri Radomljah", 
      "lat": "46.1662", 
      "lng": "14.5926", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mengeš", 
      "capital": "", 
      "population": "2070", 
      "population_proper": "2070"
    }, 
    {
      "city": "Pivka", 
      "lat": "45.6833", 
      "lng": "14.2000", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Pivka", 
      "capital": "admin", 
      "population": "2059", 
      "population_proper": "2059"
    }, 
    {
      "city": "Mozirje", 
      "lat": "46.3381", 
      "lng": "14.9572", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mozirje", 
      "capital": "admin", 
      "population": "2052", 
      "population_proper": "2052"
    }, 
    {
      "city": "Vipava", 
      "lat": "45.8476", 
      "lng": "13.9624", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vipava", 
      "capital": "admin", 
      "population": "2049", 
      "population_proper": "2049"
    }, 
    {
      "city": "Semič", 
      "lat": "45.6546", 
      "lng": "15.1783", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Semič", 
      "capital": "admin", 
      "population": "2017", 
      "population_proper": "2017"
    }, 
    {
      "city": "Limbuš", 
      "lat": "46.5581", 
      "lng": "15.5787", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Maribor", 
      "capital": "", 
      "population": "2002", 
      "population_proper": "2002"
    }, 
    {
      "city": "Radeče", 
      "lat": "46.0658", 
      "lng": "15.1728", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Radeče", 
      "capital": "admin", 
      "population": "1993", 
      "population_proper": "1993"
    }, 
    {
      "city": "Lovrenc na Pohorju", 
      "lat": "46.5381", 
      "lng": "15.3844", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Lovrenc na Pohorju", 
      "capital": "admin", 
      "population": "1992", 
      "population_proper": "1992"
    }, 
    {
      "city": "Ormož", 
      "lat": "46.4086", 
      "lng": "16.1475", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ormož", 
      "capital": "admin", 
      "population": "1962", 
      "population_proper": "1962"
    }, 
    {
      "city": "Notranje Gorice", 
      "lat": "45.9868", 
      "lng": "14.3976", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Brezovica", 
      "capital": "", 
      "population": "1950", 
      "population_proper": "1950"
    }, 
    {
      "city": "Straža", 
      "lat": "45.7864", 
      "lng": "15.0745", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Straža", 
      "capital": "admin", 
      "population": "1945", 
      "population_proper": "1945"
    }, 
    {
      "city": "Mislinja", 
      "lat": "46.4431", 
      "lng": "15.1931", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mislinja", 
      "capital": "admin", 
      "population": "1862", 
      "population_proper": "1862"
    }, 
    {
      "city": "Spodnja Idrija", 
      "lat": "46.0314", 
      "lng": "14.0256", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Idrija", 
      "capital": "", 
      "population": "1860", 
      "population_proper": "1860"
    }, 
    {
      "city": "Hrušica", 
      "lat": "46.4459", 
      "lng": "14.0130", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Jesenice", 
      "capital": "", 
      "population": "1843", 
      "population_proper": "1843"
    }, 
    {
      "city": "Zgornji Duplek", 
      "lat": "46.5092", 
      "lng": "15.7327", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Duplek", 
      "capital": "", 
      "population": "1824", 
      "population_proper": "1824"
    }, 
    {
      "city": "Kromberk", 
      "lat": "45.9592", 
      "lng": "13.6686", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Nova Gorica", 
      "capital": "", 
      "population": "1820", 
      "population_proper": "1820"
    }, 
    {
      "city": "Naklo", 
      "lat": "46.2749", 
      "lng": "14.3176", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Naklo", 
      "capital": "admin", 
      "population": "1776", 
      "population_proper": "1776"
    }, 
    {
      "city": "Bohinjska Bistrica", 
      "lat": "46.2742", 
      "lng": "13.9524", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Bohinj", 
      "capital": "admin", 
      "population": "1767", 
      "population_proper": "1767"
    }, 
    {
      "city": "Šmarje", 
      "lat": "46.2281", 
      "lng": "15.5182", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šmarje pri Jelšah", 
      "capital": "admin", 
      "population": "1755", 
      "population_proper": "1755"
    }, 
    {
      "city": "Černelavci", 
      "lat": "46.6708", 
      "lng": "16.1369", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Murska Sobota", 
      "capital": "", 
      "population": "1741", 
      "population_proper": "1741"
    }, 
    {
      "city": "Divača", 
      "lat": "45.6820", 
      "lng": "13.9702", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Divača", 
      "capital": "admin", 
      "population": "1734", 
      "population_proper": "1734"
    }, 
    {
      "city": "Kamnica", 
      "lat": "46.5746", 
      "lng": "15.6135", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Maribor", 
      "capital": "", 
      "population": "1725", 
      "population_proper": "1725"
    }, 
    {
      "city": "Radomlje", 
      "lat": "46.1780", 
      "lng": "14.6112", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Domžale", 
      "capital": "", 
      "population": "1715", 
      "population_proper": "1715"
    }, 
    {
      "city": "Cerklje na Gorenjskem", 
      "lat": "46.2488", 
      "lng": "14.4855", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cerklje na Gorenjskem", 
      "capital": "admin", 
      "population": "1710", 
      "population_proper": "1710"
    }, 
    {
      "city": "Spodnji Duplek", 
      "lat": "46.5053", 
      "lng": "15.7467", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Duplek", 
      "capital": "admin", 
      "population": "1689", 
      "population_proper": "1689"
    }, 
    {
      "city": "Britof", 
      "lat": "46.2579", 
      "lng": "14.3835", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranj", 
      "capital": "", 
      "population": "1657", 
      "population_proper": "1657"
    }, 
    {
      "city": "Dob", 
      "lat": "46.1542", 
      "lng": "14.6280", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Domžale", 
      "capital": "", 
      "population": "1638", 
      "population_proper": "1638"
    }, 
    {
      "city": "Odranci", 
      "lat": "46.5856", 
      "lng": "16.2753", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Odranci", 
      "capital": "admin", 
      "population": "1632", 
      "population_proper": "1632"
    }, 
    {
      "city": "Vodice", 
      "lat": "46.1833", 
      "lng": "14.4833", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vodice", 
      "capital": "admin", 
      "population": "1631", 
      "population_proper": "1631"
    }, 
    {
      "city": "Prebold", 
      "lat": "46.2369", 
      "lng": "15.0919", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Prebold", 
      "capital": "admin", 
      "population": "1605", 
      "population_proper": "1605"
    }, 
    {
      "city": "Kokrica", 
      "lat": "46.2638", 
      "lng": "14.3560", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranj", 
      "capital": "", 
      "population": "1595", 
      "population_proper": "1595"
    }, 
    {
      "city": "Zgornja Kungota", 
      "lat": "46.6388", 
      "lng": "15.6141", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kungota", 
      "capital": "admin", 
      "population": "1594", 
      "population_proper": "1594"
    }, 
    {
      "city": "Bovec", 
      "lat": "46.3378", 
      "lng": "13.5522", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Bovec", 
      "capital": "admin", 
      "population": "1586", 
      "population_proper": "1586"
    }, 
    {
      "city": "Radizel", 
      "lat": "46.4720", 
      "lng": "15.6537", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hoče-Slivnica", 
      "capital": "", 
      "population": "1582", 
      "population_proper": "1582"
    }, 
    {
      "city": "Zgornje Bitnje", 
      "lat": "46.2201", 
      "lng": "14.3374", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranj", 
      "capital": "", 
      "population": "1555", 
      "population_proper": "1555"
    }, 
    {
      "city": "Rakičan", 
      "lat": "46.6511", 
      "lng": "16.1981", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Murska Sobota", 
      "capital": "", 
      "population": "1543", 
      "population_proper": "1543"
    }, 
    {
      "city": "Rogatec", 
      "lat": "46.2243", 
      "lng": "15.7052", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Rogatec", 
      "capital": "admin", 
      "population": "1540", 
      "population_proper": "1540"
    }, 
    {
      "city": "Vuzenica", 
      "lat": "46.5992", 
      "lng": "15.1669", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vuzenica", 
      "capital": "admin", 
      "population": "1522", 
      "population_proper": "1522"
    }, 
    {
      "city": "Šmarje-Sap", 
      "lat": "45.9760", 
      "lng": "14.6108", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Grosuplje", 
      "capital": "", 
      "population": "1512", 
      "population_proper": "1512"
    }, 
    {
      "city": "Miren", 
      "lat": "45.8962", 
      "lng": "13.6072", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Miren-Kostanjevica", 
      "capital": "admin", 
      "population": "1506", 
      "population_proper": "1506"
    }, 
    {
      "city": "Turnišče", 
      "lat": "46.6194", 
      "lng": "16.3223", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Turnišče", 
      "capital": "admin", 
      "population": "1506", 
      "population_proper": "1506"
    }, 
    {
      "city": "Mlaka pri Kranju", 
      "lat": "46.2741", 
      "lng": "14.3475", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranj", 
      "capital": "", 
      "population": "1502", 
      "population_proper": "1502"
    }, 
    {
      "city": "Tabor", 
      "lat": "46.2108", 
      "lng": "15.0047", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Tabor", 
      "capital": "admin", 
      "population": "1494", 
      "population_proper": "1494"
    }, 
    {
      "city": "Mekinje", 
      "lat": "46.2362", 
      "lng": "14.6126", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kamnik", 
      "capital": "", 
      "population": "1493", 
      "population_proper": "1493"
    }, 
    {
      "city": "Dol pri Hrastniku", 
      "lat": "46.1425", 
      "lng": "15.1170", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hrastnik", 
      "capital": "", 
      "population": "1493", 
      "population_proper": "1493"
    }, 
    {
      "city": "Bakovci", 
      "lat": "46.6162", 
      "lng": "16.1457", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Murska Sobota", 
      "capital": "", 
      "population": "1493", 
      "population_proper": "1493"
    }, 
    {
      "city": "Dragomer", 
      "lat": "46.0189", 
      "lng": "14.3820", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Log-Dragomer", 
      "capital": "admin", 
      "population": "1464", 
      "population_proper": "1464"
    }, 
    {
      "city": "Pekre", 
      "lat": "46.5438", 
      "lng": "15.5917", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Maribor", 
      "capital": "", 
      "population": "1464", 
      "population_proper": "1464"
    }, 
    {
      "city": "Spodnje Škofije", 
      "lat": "45.5716", 
      "lng": "13.7917", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Koper", 
      "capital": "", 
      "population": "1455", 
      "population_proper": "1455"
    }, 
    {
      "city": "Kranjska Gora", 
      "lat": "46.4854", 
      "lng": "13.7871", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranjska Gora", 
      "capital": "admin", 
      "population": "1452", 
      "population_proper": "1452"
    }, 
    {
      "city": "Šentjernej", 
      "lat": "45.8389", 
      "lng": "15.3361", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šentjernej", 
      "capital": "admin", 
      "population": "1441", 
      "population_proper": "1441"
    }, 
    {
      "city": "Cerkno", 
      "lat": "46.1283", 
      "lng": "13.9915", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cerkno", 
      "capital": "admin", 
      "population": "1425", 
      "population_proper": "1425"
    }, 
    {
      "city": "Oplotnica", 
      "lat": "46.3860", 
      "lng": "15.4458", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Oplotnica", 
      "capital": "admin", 
      "population": "1420", 
      "population_proper": "1420"
    }, 
    {
      "city": "Trnovlje pri Celju", 
      "lat": "46.2524", 
      "lng": "15.2930", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Celje", 
      "capital": "", 
      "population": "1409", 
      "population_proper": "1409"
    }, 
    {
      "city": "Dekani", 
      "lat": "45.5469", 
      "lng": "13.8146", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Koper", 
      "capital": "", 
      "population": "1409", 
      "population_proper": "1409"
    }, 
    {
      "city": "Šmartno", 
      "lat": "46.0441", 
      "lng": "14.8466", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šmartno pri Litiji", 
      "capital": "admin", 
      "population": "1395", 
      "population_proper": "1395"
    }, 
    {
      "city": "Razvanje", 
      "lat": "46.5133", 
      "lng": "15.6343", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Maribor", 
      "capital": "", 
      "population": "1386", 
      "population_proper": "1386"
    }, 
    {
      "city": "Log", 
      "lat": "46.0104", 
      "lng": "14.3569", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Log-Dragomer", 
      "capital": "", 
      "population": "1379", 
      "population_proper": "1379"
    }, 
    {
      "city": "Mirna", 
      "lat": "45.9476", 
      "lng": "15.0664", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mirna", 
      "capital": "admin", 
      "population": "1371", 
      "population_proper": "1371"
    }, 
    {
      "city": "Šmarca", 
      "lat": "46.1971", 
      "lng": "14.5964", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kamnik", 
      "capital": "", 
      "population": "1365", 
      "population_proper": "1365"
    }, 
    {
      "city": "Selnica ob Dravi", 
      "lat": "46.5514", 
      "lng": "15.4947", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Selnica ob Dravi", 
      "capital": "admin", 
      "population": "1348", 
      "population_proper": "1348"
    }, 
    {
      "city": "Sveti Anton", 
      "lat": "45.5261", 
      "lng": "13.8354", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Koper", 
      "capital": "", 
      "population": "1343", 
      "population_proper": "1343"
    }, 
    {
      "city": "Deskle", 
      "lat": "46.0534", 
      "lng": "13.6135", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kanal ob Soči", 
      "capital": "", 
      "population": "1324", 
      "population_proper": "1324"
    }, 
    {
      "city": "Brestrnica", 
      "lat": "46.5667", 
      "lng": "15.5667", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Maribor", 
      "capital": "", 
      "population": "1299", 
      "population_proper": "1299"
    }, 
    {
      "city": "Hotinja Vas", 
      "lat": "46.4675", 
      "lng": "15.6721", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hoče-Slivnica", 
      "capital": "", 
      "population": "1295", 
      "population_proper": "1295"
    }, 
    {
      "city": "Bilje", 
      "lat": "45.8965", 
      "lng": "13.6470", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Miren-Kostanjevica", 
      "capital": "", 
      "population": "1271", 
      "population_proper": "1271"
    }, 
    {
      "city": "Dornava", 
      "lat": "46.4299", 
      "lng": "15.9488", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dornava", 
      "capital": "admin", 
      "population": "1263", 
      "population_proper": "1263"
    }, 
    {
      "city": "Kidričevo", 
      "lat": "46.4060", 
      "lng": "15.7983", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kidričevo", 
      "capital": "admin", 
      "population": "1257", 
      "population_proper": "1257"
    }, 
    {
      "city": "Šmartno pri Slovenj Gradcu", 
      "lat": "46.4909", 
      "lng": "15.1077", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Slovenj Gradec", 
      "capital": "", 
      "population": "1257", 
      "population_proper": "1257"
    }, 
    {
      "city": "Topolšica", 
      "lat": "46.4034", 
      "lng": "15.0183", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šoštanj", 
      "capital": "", 
      "population": "1191", 
      "population_proper": "1191"
    }, 
    {
      "city": "Rogoza", 
      "lat": "46.5000", 
      "lng": "15.6841", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hoče-Slivnica", 
      "capital": "", 
      "population": "1187", 
      "population_proper": "1187"
    }, 
    {
      "city": "Horjul", 
      "lat": "46.0230", 
      "lng": "14.2981", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Horjul", 
      "capital": "admin", 
      "population": "1169", 
      "population_proper": "1169"
    }, 
    {
      "city": "Prvačina", 
      "lat": "45.8879", 
      "lng": "13.7231", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Nova Gorica", 
      "capital": "", 
      "population": "1169", 
      "population_proper": "1169"
    }, 
    {
      "city": "Zgornje Pirniče", 
      "lat": "46.1414", 
      "lng": "14.4294", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Medvode", 
      "capital": "", 
      "population": "1163", 
      "population_proper": "1163"
    }, 
    {
      "city": "Črenšovci", 
      "lat": "46.5747", 
      "lng": "16.2937", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Črenšovci", 
      "capital": "admin", 
      "population": "1151", 
      "population_proper": "1151"
    }, 
    {
      "city": "Izlake", 
      "lat": "46.1525", 
      "lng": "14.8940", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Zagorje ob Savi", 
      "capital": "", 
      "population": "1146", 
      "population_proper": "1146"
    }, 
    {
      "city": "Kanal", 
      "lat": "46.0880", 
      "lng": "13.6347", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kanal ob Soči", 
      "capital": "admin", 
      "population": "1142", 
      "population_proper": "1142"
    }, 
    {
      "city": "Ljubečna", 
      "lat": "46.2551", 
      "lng": "15.3231", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Celje", 
      "capital": "", 
      "population": "1141", 
      "population_proper": "1141"
    }, 
    {
      "city": "Gorenja Vas", 
      "lat": "46.1069", 
      "lng": "14.1451", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Gorenja Vas-Poljane", 
      "capital": "admin", 
      "population": "1132", 
      "population_proper": "1132"
    }, 
    {
      "city": "Rožna Dolina", 
      "lat": "45.9425", 
      "lng": "13.6397", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šempeter-Vrtojba", 
      "capital": "", 
      "population": "1127", 
      "population_proper": "1127"
    }, 
    {
      "city": "Hrvatini", 
      "lat": "45.5822", 
      "lng": "13.7561", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Koper", 
      "capital": "", 
      "population": "1126", 
      "population_proper": "1126"
    }, 
    {
      "city": "Zgornja Polskava", 
      "lat": "46.4258", 
      "lng": "15.6070", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Slovenska Bistrica", 
      "capital": "", 
      "population": "1126", 
      "population_proper": "1126"
    }, 
    {
      "city": "Poljčane", 
      "lat": "46.3135", 
      "lng": "15.5791", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Poljčane", 
      "capital": "admin", 
      "population": "1118", 
      "population_proper": "1118"
    }, 
    {
      "city": "Pragersko", 
      "lat": "46.3955", 
      "lng": "15.6614", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Slovenska Bistrica", 
      "capital": "", 
      "population": "1101", 
      "population_proper": "1101"
    }, 
    {
      "city": "Krog", 
      "lat": "46.6364", 
      "lng": "16.1364", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Murska Sobota", 
      "capital": "", 
      "population": "1096", 
      "population_proper": "1096"
    }, 
    {
      "city": "Ljubno", 
      "lat": "46.3333", 
      "lng": "14.8333", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ljubno", 
      "capital": "admin", 
      "population": "1094", 
      "population_proper": "1094"
    }, 
    {
      "city": "Višnja Gora", 
      "lat": "45.9580", 
      "lng": "14.7422", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ivančna Gorica", 
      "capital": "", 
      "population": "1090", 
      "population_proper": "1090"
    }, 
    {
      "city": "Kobarid", 
      "lat": "46.2464", 
      "lng": "13.5780", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kobarid", 
      "capital": "admin", 
      "population": "1085", 
      "population_proper": "1085"
    }, 
    {
      "city": "Benedikt", 
      "lat": "46.6065", 
      "lng": "15.8842", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Benedikt", 
      "capital": "admin", 
      "population": "1078", 
      "population_proper": "1078"
    }, 
    {
      "city": "Selnica", 
      "lat": "46.6859", 
      "lng": "15.6919", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šentilj", 
      "capital": "", 
      "population": "1077", 
      "population_proper": "1077"
    }, 
    {
      "city": "Šempas", 
      "lat": "45.9286", 
      "lng": "13.7433", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Nova Gorica", 
      "capital": "", 
      "population": "1066", 
      "population_proper": "1066"
    }, 
    {
      "city": "Hrastje", 
      "lat": "46.2238", 
      "lng": "14.3814", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šenčur", 
      "capital": "", 
      "population": "1040", 
      "population_proper": "1040"
    }, 
    {
      "city": "Lipovci", 
      "lat": "46.6259", 
      "lng": "16.2286", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Beltinci", 
      "capital": "", 
      "population": "1030", 
      "population_proper": "1030"
    }, 
    {
      "city": "Golnik", 
      "lat": "46.3315", 
      "lng": "14.3306", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kranj", 
      "capital": "", 
      "population": "1026", 
      "population_proper": "1026"
    }, 
    {
      "city": "Gornji Grad", 
      "lat": "46.2961", 
      "lng": "14.8052", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Gornji Grad", 
      "capital": "admin", 
      "population": "1016", 
      "population_proper": "1016"
    }, 
    {
      "city": "Mirna Peč", 
      "lat": "45.8580", 
      "lng": "15.0876", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mirna Peč", 
      "capital": "admin", 
      "population": "1015", 
      "population_proper": "1015"
    }, 
    {
      "city": "Pobegi", 
      "lat": "45.5400", 
      "lng": "13.7941", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Koper", 
      "capital": "", 
      "population": "1011", 
      "population_proper": "1011"
    }, 
    {
      "city": "Podgorje", 
      "lat": "46.2174", 
      "lng": "14.5913", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kamnik", 
      "capital": "", 
      "population": "1009", 
      "population_proper": "1009"
    }, 
    {
      "city": "Središče ob Dravi", 
      "lat": "46.3933", 
      "lng": "16.2722", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Središče ob Dravi", 
      "capital": "admin", 
      "population": "984", 
      "population_proper": "984"
    }, 
    {
      "city": "Moravče", 
      "lat": "46.1356", 
      "lng": "14.7439", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Moravče", 
      "capital": "admin", 
      "population": "957", 
      "population_proper": "957"
    }, 
    {
      "city": "Dobrovnik", 
      "lat": "46.6515", 
      "lng": "16.3479", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dobrovnik", 
      "capital": "admin", 
      "population": "948", 
      "population_proper": "948"
    }, 
    {
      "city": "Dobrova", 
      "lat": "46.0533", 
      "lng": "14.4144", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dobrova-Polhov Gradec", 
      "capital": "admin", 
      "population": "921", 
      "population_proper": "921"
    }, 
    {
      "city": "Veržej", 
      "lat": "46.5818", 
      "lng": "16.1623", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Veržej", 
      "capital": "admin", 
      "population": "900", 
      "population_proper": "900"
    }, 
    {
      "city": "Komenda", 
      "lat": "46.2073", 
      "lng": "14.5390", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Komenda", 
      "capital": "admin", 
      "population": "896", 
      "population_proper": "896"
    }, 
    {
      "city": "Dolenjske Toplice", 
      "lat": "45.7545", 
      "lng": "15.0583", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dolenjske Toplice", 
      "capital": "admin", 
      "population": "882", 
      "population_proper": "882"
    }, 
    {
      "city": "Nazarje", 
      "lat": "46.3202", 
      "lng": "14.9531", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Nazarje", 
      "capital": "admin", 
      "population": "880", 
      "population_proper": "880"
    }, 
    {
      "city": "Velika Polana", 
      "lat": "46.5719", 
      "lng": "16.3472", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Velika Polana", 
      "capital": "admin", 
      "population": "870", 
      "population_proper": "870"
    }, 
    {
      "city": "Vitanje", 
      "lat": "46.3825", 
      "lng": "15.2956", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vitanje", 
      "capital": "admin", 
      "population": "859", 
      "population_proper": "859"
    }, 
    {
      "city": "Gorišnica", 
      "lat": "46.4122", 
      "lng": "16.0131", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Gorišnica", 
      "capital": "admin", 
      "population": "856", 
      "population_proper": "856"
    }, 
    {
      "city": "Pesnica", 
      "lat": "46.6099", 
      "lng": "15.6714", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Pesnica", 
      "capital": "admin", 
      "population": "843", 
      "population_proper": "843"
    }, 
    {
      "city": "Sodražica", 
      "lat": "45.7616", 
      "lng": "14.6363", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sodražica", 
      "capital": "admin", 
      "population": "842", 
      "population_proper": "842"
    }, 
    {
      "city": "Stari Trg", 
      "lat": "45.7142", 
      "lng": "14.4695", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Loška Dolina", 
      "capital": "admin", 
      "population": "838", 
      "population_proper": "838"
    }, 
    {
      "city": "Preddvor", 
      "lat": "46.3052", 
      "lng": "14.4203", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Preddvor", 
      "capital": "admin", 
      "population": "835", 
      "population_proper": "835"
    }, 
    {
      "city": "Zgornja Hajdina", 
      "lat": "46.4057", 
      "lng": "15.8385", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hajdina", 
      "capital": "admin", 
      "population": "804", 
      "population_proper": "804"
    }, 
    {
      "city": "Starše", 
      "lat": "46.4664", 
      "lng": "15.7675", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Starše", 
      "capital": "admin", 
      "population": "757", 
      "population_proper": "757"
    }, 
    {
      "city": "Sveta Trojica v Slovenskih Goricah", 
      "lat": "46.5756", 
      "lng": "15.8769", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sveta Trojica v Slovenskih Goricah", 
      "capital": "admin", 
      "population": "754", 
      "population_proper": "754"
    }, 
    {
      "city": "Moravske-Toplice", 
      "lat": "46.6927", 
      "lng": "16.2281", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Moravske Toplice", 
      "capital": "admin", 
      "population": "752", 
      "population_proper": "752"
    }, 
    {
      "city": "Velike Lašče", 
      "lat": "45.8363", 
      "lng": "14.6377", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Velike Lašče", 
      "capital": "admin", 
      "population": "724", 
      "population_proper": "724"
    }, 
    {
      "city": "Mokronog", 
      "lat": "45.9426", 
      "lng": "15.1490", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Mokronog-Trebelno", 
      "capital": "admin", 
      "population": "700", 
      "population_proper": "700"
    }, 
    {
      "city": "Kostanjevica na Krki", 
      "lat": "45.8463", 
      "lng": "15.4249", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kostanjevica na Krki", 
      "capital": "admin", 
      "population": "689", 
      "population_proper": "689"
    }, 
    {
      "city": "Komen", 
      "lat": "45.8159", 
      "lng": "13.7507", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Komen", 
      "capital": "admin", 
      "population": "642", 
      "population_proper": "642"
    }, 
    {
      "city": "Šmartno", 
      "lat": "46.3297", 
      "lng": "15.0325", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šmartno ob Paki", 
      "capital": "admin", 
      "population": "636", 
      "population_proper": "636"
    }, 
    {
      "city": "Kozje", 
      "lat": "46.0740", 
      "lng": "15.5590", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kozje", 
      "capital": "admin", 
      "population": "634", 
      "population_proper": "634"
    }, 
    {
      "city": "Puconci", 
      "lat": "46.7039", 
      "lng": "16.1572", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Puconci", 
      "capital": "admin", 
      "population": "633", 
      "population_proper": "633"
    }, 
    {
      "city": "Grad", 
      "lat": "46.7977", 
      "lng": "16.0984", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Grad", 
      "capital": "admin", 
      "population": "620", 
      "population_proper": "620"
    }, 
    {
      "city": "Majšperk", 
      "lat": "46.3500", 
      "lng": "15.7333", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Majšperk", 
      "capital": "admin", 
      "population": "606", 
      "population_proper": "606"
    }, 
    {
      "city": "Videm", 
      "lat": "45.8484", 
      "lng": "14.6944", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dobrepolje", 
      "capital": "admin", 
      "population": "590", 
      "population_proper": "590"
    }, 
    {
      "city": "Podčetrtek", 
      "lat": "46.1573", 
      "lng": "15.5974", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Podčetrtek", 
      "capital": "admin", 
      "population": "578", 
      "population_proper": "578"
    }, 
    {
      "city": "Zgornje Jezersko", 
      "lat": "46.3951", 
      "lng": "14.4966", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Jezersko", 
      "capital": "admin", 
      "population": "558", 
      "population_proper": "558"
    }, 
    {
      "city": "Apače", 
      "lat": "46.6967", 
      "lng": "15.9111", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Apače", 
      "capital": "admin", 
      "population": "543", 
      "population_proper": "543"
    }, 
    {
      "city": "Kobilje", 
      "lat": "46.6837", 
      "lng": "16.3953", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kobilje", 
      "capital": "admin", 
      "population": "542", 
      "population_proper": "542"
    }, 
    {
      "city": "Dobrna", 
      "lat": "46.3381", 
      "lng": "15.2293", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dobrna", 
      "capital": "admin", 
      "population": "536", 
      "population_proper": "536"
    }, 
    {
      "city": "Zgornje Gorje", 
      "lat": "46.3801", 
      "lng": "14.0684", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Gorje", 
      "capital": "admin", 
      "population": "532", 
      "population_proper": "532"
    }, 
    {
      "city": "Rečica", 
      "lat": "46.3247", 
      "lng": "14.9228", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Rečica ob Savinji", 
      "capital": "admin", 
      "population": "516", 
      "population_proper": "516"
    }, 
    {
      "city": "Križevci", 
      "lat": "46.5631", 
      "lng": "16.1399", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Križevci", 
      "capital": "admin", 
      "population": "499", 
      "population_proper": "499"
    }, 
    {
      "city": "Markovci", 
      "lat": "46.3956", 
      "lng": "15.9314", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Markovci", 
      "capital": "admin", 
      "population": "495", 
      "population_proper": "495"
    }, 
    {
      "city": "Šmarješke Toplice", 
      "lat": "45.8622", 
      "lng": "15.2214", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šmarješke Toplice", 
      "capital": "admin", 
      "population": "492", 
      "population_proper": "492"
    }, 
    {
      "city": "Videm pri Ptuju", 
      "lat": "46.3699", 
      "lng": "15.8935", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Videm", 
      "capital": "admin", 
      "population": "451", 
      "population_proper": "451"
    }, 
    {
      "city": "Cirkulane", 
      "lat": "46.3436", 
      "lng": "15.9941", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cirkulane", 
      "capital": "admin", 
      "population": "451", 
      "population_proper": "451"
    }, 
    {
      "city": "Lukovica", 
      "lat": "46.1686", 
      "lng": "14.6892", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Lukovica", 
      "capital": "admin", 
      "population": "438", 
      "population_proper": "438"
    }, 
    {
      "city": "Kuzma", 
      "lat": "46.8333", 
      "lng": "16.0833", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kuzma", 
      "capital": "admin", 
      "population": "429", 
      "population_proper": "429"
    }, 
    {
      "city": "Cankova", 
      "lat": "46.7193", 
      "lng": "16.0179", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cankova", 
      "capital": "admin", 
      "population": "416", 
      "population_proper": "416"
    }, 
    {
      "city": "Gornji Petrovci", 
      "lat": "46.8050", 
      "lng": "16.2172", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Gornji Petrovci", 
      "capital": "admin", 
      "population": "411", 
      "population_proper": "411"
    }, 
    {
      "city": "Tišina", 
      "lat": "46.6558", 
      "lng": "16.0933", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Tišina", 
      "capital": "admin", 
      "population": "408", 
      "population_proper": "408"
    }, 
    {
      "city": "Ribnica", 
      "lat": "46.5372", 
      "lng": "15.2733", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Ribnica na Pohorju", 
      "capital": "admin", 
      "population": "404", 
      "population_proper": "404"
    }, 
    {
      "city": "Luče", 
      "lat": "46.3565", 
      "lng": "14.7436", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Luče", 
      "capital": "admin", 
      "population": "402", 
      "population_proper": "402"
    }, 
    {
      "city": "Šalovci", 
      "lat": "46.8250", 
      "lng": "16.2981", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šalovci", 
      "capital": "admin", 
      "population": "392", 
      "population_proper": "392"
    }, 
    {
      "city": "Juršinci", 
      "lat": "46.4853", 
      "lng": "15.9710", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Juršinci", 
      "capital": "admin", 
      "population": "381", 
      "population_proper": "381"
    }, 
    {
      "city": "Podlehnik", 
      "lat": "46.3361", 
      "lng": "15.8786", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Podlehnik", 
      "capital": "admin", 
      "population": "378", 
      "population_proper": "378"
    }, 
    {
      "city": "Braslovče", 
      "lat": "46.2884", 
      "lng": "15.0386", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Braslovče", 
      "capital": "admin", 
      "population": "378", 
      "population_proper": "378"
    }, 
    {
      "city": "Trnovska Vas", 
      "lat": "46.5231", 
      "lng": "15.8978", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Trnovska Vas", 
      "capital": "admin", 
      "population": "369", 
      "population_proper": "369"
    }, 
    {
      "city": "Jurovski Dol", 
      "lat": "46.6087", 
      "lng": "15.7796", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sveti Jurij v Slovenskih Goricah", 
      "capital": "admin", 
      "population": "361", 
      "population_proper": "361"
    }, 
    {
      "city": "Hrib-Loški Potok", 
      "lat": "45.7015", 
      "lng": "14.5901", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Loški Potok", 
      "capital": "admin", 
      "population": "353", 
      "population_proper": "353"
    }, 
    {
      "city": "Vitomarci", 
      "lat": "46.5248", 
      "lng": "15.9346", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sveti Andraž v Slovenskih Goricah", 
      "capital": "admin", 
      "population": "341", 
      "population_proper": "341"
    }, 
    {
      "city": "Dobrovo", 
      "lat": "45.9989", 
      "lng": "13.5296", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Brda", 
      "capital": "admin", 
      "population": "334", 
      "population_proper": "334"
    }, 
    {
      "city": "Šentrupert", 
      "lat": "45.9769", 
      "lng": "15.0897", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šentrupert", 
      "capital": "admin", 
      "population": "310", 
      "population_proper": "310"
    }, 
    {
      "city": "Podvelka", 
      "lat": "46.5864", 
      "lng": "15.3286", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Podvelka", 
      "capital": "admin", 
      "population": "299", 
      "population_proper": "299"
    }, 
    {
      "city": "Nova Vas", 
      "lat": "45.7726", 
      "lng": "14.5064", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Bloke", 
      "capital": "admin", 
      "population": "293", 
      "population_proper": "293"
    }, 
    {
      "city": "Hodoš", 
      "lat": "46.8285", 
      "lng": "16.3239", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Hodoš", 
      "capital": "admin", 
      "population": "280", 
      "population_proper": "280"
    }, 
    {
      "city": "Dol", 
      "lat": "46.0884", 
      "lng": "14.6425", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dol pri Ljubljani", 
      "capital": "admin", 
      "population": "277", 
      "population_proper": "277"
    }, 
    {
      "city": "Tomaž pri Ormožu", 
      "lat": "46.4833", 
      "lng": "16.0794", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sveti Tomaž", 
      "capital": "admin", 
      "population": "254", 
      "population_proper": "254"
    }, 
    {
      "city": "Bistrica ob Sotli", 
      "lat": "46.0589", 
      "lng": "15.6642", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Bistrica ob Sotli", 
      "capital": "admin", 
      "population": "235", 
      "population_proper": "235"
    }, 
    {
      "city": "Škocjan", 
      "lat": "45.9069", 
      "lng": "15.2914", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Škocjan", 
      "capital": "admin", 
      "population": "233", 
      "population_proper": "233"
    }, 
    {
      "city": "Makole", 
      "lat": "46.3174", 
      "lng": "15.6669", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Makole", 
      "capital": "admin", 
      "population": "221", 
      "population_proper": "221"
    }, 
    {
      "city": "Sveti Jurij", 
      "lat": "46.5683", 
      "lng": "16.0203", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sveti Jurij ob Ščavnici", 
      "capital": "admin", 
      "population": "209", 
      "population_proper": "209"
    }, 
    {
      "city": "Solčava", 
      "lat": "46.4201", 
      "lng": "14.6918", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Solčava", 
      "capital": "admin", 
      "population": "208", 
      "population_proper": "208"
    }, 
    {
      "city": "Destrnik", 
      "lat": "46.4923", 
      "lng": "15.8801", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Destrnik", 
      "capital": "admin", 
      "population": "186", 
      "population_proper": "186"
    }, 
    {
      "city": "Cerkvenjak", 
      "lat": "46.5660", 
      "lng": "15.9429", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Cerkvenjak", 
      "capital": "admin", 
      "population": "163", 
      "population_proper": "163"
    }, 
    {
      "city": "Sveta Ana", 
      "lat": "46.6497", 
      "lng": "15.8453", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Sveta Ana", 
      "capital": "admin", 
      "population": "159", 
      "population_proper": "159"
    }, 
    {
      "city": "Razkrižje", 
      "lat": "46.5182", 
      "lng": "16.2882", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Razkrižje", 
      "capital": "admin", 
      "population": "141", 
      "population_proper": "141"
    }, 
    {
      "city": "Dobje", 
      "lat": "46.1369", 
      "lng": "15.3945", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Dobje", 
      "capital": "admin", 
      "population": "114", 
      "population_proper": "114"
    }, 
    {
      "city": "Osilnica", 
      "lat": "45.5289", 
      "lng": "14.6983", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Osilnica", 
      "capital": "admin", 
      "population": "76", 
      "population_proper": "76"
    }, 
    {
      "city": "Vransko", 
      "lat": "46.1720", 
      "lng": "14.8217", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Vransko", 
      "capital": "admin", 
      "population": "11", 
      "population_proper": "11"
    }, 
    {
      "city": "Kostel", 
      "lat": "45.5088", 
      "lng": "14.9100", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Kostel", 
      "capital": "admin", 
      "population": "10", 
      "population_proper": "10"
    }, 
    {
      "city": "Šentilj", 
      "lat": "46.6817", 
      "lng": "15.6481", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Šentilj", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Žužemberk", 
      "lat": "45.8339", 
      "lng": "14.9292", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Žužemberk", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Zavrč", 
      "lat": "46.3917", 
      "lng": "16.0497", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Zavrč", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Žetale", 
      "lat": "46.2750", 
      "lng": "15.7939", 
      "country": "Slovenia", 
      "iso2": "SI", 
      "admin_name": "Žetale", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }
  ]